# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

os:
  - osx

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

env:
  - TOOLCHAIN=osx-10-7 CONFIG=Release
  - TOOLCHAIN=ios-nocodesign CONFIG=Release EXTRA="--ios-multiarch"

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then easy_install3 --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"

  - export PATH="${POLLY_ROOT}/bin:${PATH}"
  - export XCODE_XCCONFIG_FILE="${POLLY_ROOT}/scripts/NoCodeSign.xcconfig"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  #- export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:
  - build.py --toolchain ${TOOLCHAIN} --config ${CONFIG} --verbose ${EXTRA}

deploy:
  provider: bintray
  file: .bintray.json
  user: speps
  key:
    secure: DG49j2AIMm6ga/lM8XaZ0QGXrciG2t5FQJRtvFY3ujMrJvcu6q3WO2Bnmzvh/RiiOpXAZ7MLEXaJKS0/iE7RshE58lAOS7D3lzuDBQphhkem/tpM9tRc8/3VL07dwB6h2KrCs1u0WEC/qJdE5SyF2eu/43dkng+ctcYUSKFff0yL+wDRTNuo/C+xA2buoNeUN+2R/xJrfEBDX3pxQ+UjBYENbCTIvamJ5N1nWMXqCEP5j6x2DmT/x0WTGJMzQ2amNVsuD6usL/WLJb4BnhnaQhsMuFnLHxQZSzDNsTiV5yl52xD0ITtsIUOgGW5zjR0h9Nth1iM6JeeUfDbiYjJcNQpYQD28LnUk2sTgxYF/ey1JvN8buKUkVcPxgneLbJdKGo+UgpIUtYn8kUAvcCUjTjc1zrqKT+cpuaSkb6WI9U3qqMZU3OjORnBO4HVFxBFAP6BL4P2Sc08hcw8f568xFIWx1maA0+/go6hBa1WKe3PYbUcjh2LGIhEgTkLiTH//xWaxHbUkcWSZLelJyy8FfbgNtMbWIGFk4JSq/owO5cem64bBpZrO3vuO3ewyDrPfn1QPSLo7kKjDvs5nVI0Z7IMynFyzv6KcKSwGmLPHhySj/Cv33vey+Ua/chwHx/Gl8w7W+acl/Wnq7ZAaAnvW79mGovqJcmOd/TguryOqUp8=
