# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  matrix:
    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release
      PLUGIN_FOLDER: x86
    - TOOLCHAIN: "vs-14-2015-win64"
      CONFIG: Release
      PLUGIN_FOLDER: x64

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # If submodules used
  # - git submodule update --init --recursive

build_script:
  - cmd: python %POLLY_ROOT%\bin\build.py --toolchain "%TOOLCHAIN%" --config "%CONFIG%" --verbose

after_build:
  - cmd: cd _output
  - cmd: md Plugins\%PLUGIN_FOLDER%
  - cmd: copy %TOOLCHAIN%\Release\GrumpyMovieTexture.dll Plugins\%PLUGIN_FOLDER%
  - cmd: 7z a output.zip Plugins

artifacts:
  - path: _output\output.zip

deploy:
- provider: BinTray
  username: speps
  api_key:
    secure: IkcYbqlqyL87MqKBJkcFI9j3aX42CKUmFxPcebrfEHr4EsQqcuHuZik9Zx8zRI6k
  subject: speps
  repo: GrumpyMovieTexture
  package: Plugins
  version: Latest
  publish: true
  override: true
  explode: true
  artifact: _output\output.zip
